apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-app"
  namespace: "default"
  labels:
    app: "my-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      containers:
      - name: "gke-image-1"
        image: "gcr.io/devops-cicd-412116/gke-image:v3.0"


---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
