#devops-cicd-412116/github_sanchayana2007_app_kubrntes_devops/main//

steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sanchayana2007/App_Kubrntes_DEVOPS.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t',  'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

# kubectl set image deployment/cicd-app-1 runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deploy.yaml
  - --image=${_CINAME}:${_VERSION}
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-terraform-project-dev'

substitutions:
  _PROJECT_ID : devops-cicd-412116
  _CINAME : gke-image
  _VERSION : v3.0
