#devops-cicd-412116/github_sanchayana2007_app_kubrntes_devops/main//

steps:
- name: 'gcr.io/cloud-builders/git'
  id: PreRequsite
  args: ['clone', 'https://github.com/sanchayana2007/App_Kubrntes_DEVOPS.git']

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build','-t',  'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']
  
- name: gcr.io/cloud-builders/bash
  id: SonarQube Scan
  args:
    - echo "SAST on the Build"

- name: 'gcr.io/cloud-builders/docker'
  id: PublishImage
  args: ['push','gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']


- name: gcr.io/cloud-builders/bash
  id: QA_Test
  args:
    - echo "Implenet a QA on teh docker Image"
  
  # kubectl set image deployment/ runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: 'bash'
  args:
    - '-c'
    - |
         PROJECT=$$(gcloud config get-value core/project)          
         gke-gcloud-auth-plugin --version
         export USE_GKE_GCLOUD_AUTH_PLUGIN=True
         gcloud container clusters get-credentials "gke-terraform-project-dev" --project "devops-cicd-412116"  --zone "us-east1"  
         kubectl apply -f deploy.yaml

 
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-terraform-project-dev'

substitutions:
  _PROJECT_ID : devops-cicd-412116
  _CINAME : gke-image
  _VERSION : v3.0


